/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#eeefff",
        "tertiary-fixed": "#dae2fd",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#b9c7df",
        "surface-container-high": "#e6e8ea",
        "primary": "#004ac6",
        "on-surface": "#191c1e",
        "secondary": "#515f74",
        "on-primary-fixed": "#00174b",
        "error": "#ba1a1a",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#131b2e",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#0053db",
        "inverse-primary": "#b4c5ff",
        "on-surface-variant": "#434655",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#3a485b",
        "secondary-container": "#d5e3fc",
        "background": "#f7f9fb",
        "on-secondary-fixed": "#0d1c2e",
        "primary-fixed": "#dbe1ff",
        "outline-variant": "#c3c6d7",
        "tertiary": "#4d556b",
        "on-primary-fixed-variant": "#003ea8",
        "on-tertiary-container": "#eef0ff",
        "on-error": "#ffffff",
        "outline": "#737686",
        "surface-container": "#eceef0",
        "surface-container-highest": "#e0e3e5",
        "inverse-on-surface": "#eff1f3",
        "primary-container": "#2563eb",
        "surface": "#f7f9fb",
        "on-background": "#191c1e",
        "secondary-fixed": "#d5e3fc",
        "tertiary-fixed-dim": "#bec6e0",
        "tertiary-container": "#656d84",
        "on-tertiary-fixed-variant": "#3f465c",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-dim": "#d8dadc",
        "primary-fixed-dim": "#b4c5ff",
        "surface-bright": "#f7f9fb",
        "inverse-surface": "#2d3133",
        "on-secondary-container": "#57657a",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e0e3e5"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
